releases:
  - name: prometheus
    namespace: ror-poc
    chart: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
    createNamespace: true
    values:
      - additionalPrometheusRulesMap:
          postgresql-alerts:
            groups:
              - name: postgresql
                interval: 30s
                rules:
                  # Low cache hit ratio
                  - alert: LowCacheHitRatio
                    expr: pg_stat_database_blks_hit / (pg_stat_database_blks_hit + pg_stat_database_blks_read) < 0.95
                    for: 10m
                    labels:
                      severity: warning
                    annotations:
                      summary: "Cache hit ratio below 95%"
                      description: "PostgreSQL cache hit ratio is {{ $value | humanizePercentage }} on {{ $labels.instance }}"

                  # High connection usage
                  - alert: HighConnectionUsage
                    expr: pg_stat_activity_count / pg_settings_max_connections > 0.8
                    for: 5m
                    labels:
                      severity: warning
                    annotations:
                      summary: "PostgreSQL connections above 80% of max"
                      description: "Connection usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"

                  # Replication lag
                  - alert: HighReplicationLag
                    expr: pg_replication_lag_seconds > 30
                    for: 5m
                    labels:
                      severity: critical
                    annotations:
                      summary: "Replication lag above 30 seconds"
                      description: "Replication lag is {{ $value }} seconds on {{ $labels.instance }}"

                  # Disk space
                  - alert: LowDiskSpace
                    expr: (pg_database_size_bytes / node_filesystem_size_bytes) > 0.85
                    for: 5m
                    labels:
                      severity: warning
                    annotations:
                      summary: "Database disk usage above 85%"
                      description: "Database disk usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"

                  # High CPU usage
                  - alert: HighPostgreSQLCPU
                    expr: rate(process_cpu_seconds_total{job=~".*postgresql.*"}[5m]) > 0.8
                    for: 5m
                    labels:
                      severity: warning
                    annotations:
                      summary: "PostgreSQL CPU usage above 80%"
                      description: "PostgreSQL CPU usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"
          redis-alerts:
            groups:
              - name: redis
                interval: 30s
                rules:
                  # Low cache hit rate
                  - alert: LowRedisHitRate
                    expr: rate(redis_keyspace_hits_total[5m]) / (rate(redis_keyspace_hits_total[5m]) + rate(redis_keyspace_misses_total[5m])) < 0.8
                    for: 10m
                    annotations:
                      summary: "Redis cache hit rate below 80%"

                  # High memory usage
                  - alert: HighRedisMemory
                    expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.85
                    for: 5m
                    annotations:
                      summary: "Redis memory usage above 85%"

                  # High eviction rate
                  - alert: HighEvictionRate
                    expr: rate(redis_evicted_keys_total[5m]) > 100
                    for: 5m
                    annotations:
                      summary: "Redis evicting keys rapidly"

                  # Connection issues
                  - alert: RedisConnectionIssues
                    expr: redis_rejected_connections_total > 0
                    for: 1m
                    annotations:
                      summary: "Redis rejecting connections"

                  # High CPU usage
                  - alert: HighRedisCPU
                    expr: rate(redis_cpu_sys_seconds_total[5m]) + rate(redis_cpu_user_seconds_total[5m]) > 0.7
                    for: 5m
                    annotations:
                      summary: "Redis CPU usage above 70%"
                      description: "Redis CPU usage is high on {{ $labels.instance }}"
      - metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            additionalLabels:
              release: prometheus
            path: /metrics
            port: metrics
            interval: 15s

  - name: redis
    namespace: ror-poc
    chart: oci://registry-1.docker.io/bitnamicharts/redis
    version: 24.0.8
    createNamespace: true
    needs:
      - ror-poc/prometheus
    values:
      - metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            additionalLabels:
              release: prometheus
  - name: postgresql
    namespace: ror-poc
    chart: oci://registry-1.docker.io/bitnamicharts/postgresql
    version: 18.1.14
    createNamespace: true
    needs:
      - ror-poc/prometheus
    values:
      - metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            labels:
              release: prometheus
